---
title: "snp_ptm_lab_copy"
author: "Christopher Seybold"
date: "2023-11-14"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r defs}

library(purrr)
library(MASS)
set.seed(24601)
library(tidyverse)

```


```{r snp_prob}

patient_count <- 50
snp_ptm_id_count <- 100

snp_prob <- rep(rnorm(snp_ptm_id_count, 0.4, 0.2), patient_count)
snp_prob <- pmax(pmin(1, snp_prob), 0)

effect_range <- 0.2
effect_size <- sample(c(-1*effect_range, 0, effect_range),
      size = snp_ptm_id_count, replace = TRUE, prob = c(0.15, 0.7, 0.15))

ptm_wo_snp_prob <- rep(rnorm(snp_ptm_id_count, 0.3, 0.15), patient_count)
ptm_wo_snp_prob <- pmax(pmin(1, ptm_wo_snp_prob), effect_range)

lambda_ <- rep(sample(2:8, size = snp_ptm_id_count, replace = TRUE), patient_count)

pep_count = rpois(patient_count*snp_ptm_id_count, lambda = lambda_)
pep_count = replace(pep_count, pep_count==0, 1)

pep_w_snp_count <- numeric(patient_count * snp_ptm_id_count)
for (i in 1:(patient_count*snp_ptm_id_count)) {
  pep_w_snp_count[i] = min(pep_count[i], sample(c(0, 0.5, 1),
                          size = 1, replace = TRUE,
                          prob = c((1 - snp_prob[i])^2,
                            snp_prob[i]^2,
                            max(1 - ((1 - snp_prob[i])^2 + snp_prob[i]^2), 0))))
}
pep_w_snp_count[pep_w_snp_count == 1] <- pep_count[pep_w_snp_count == 1]
pep_w_snp_count[pep_w_snp_count == 0.5] <- rbinom(length(pep_w_snp_count[pep_w_snp_count == 0.5]),
                                                  pep_count[pep_w_snp_count == 0.5], 0.5)

pep_w_ptm_snp = rbinom(patient_count * snp_ptm_id_count,
                       pep_w_snp_count, ptm_wo_snp_prob + effect_size)

pep_w_ptm_nosnp = rbinom(patient_count * snp_ptm_id_count,
                         pep_count - pep_w_snp_count, ptm_wo_snp_prob)

pep_w_snp_long <- numeric(0)
for (i in 1:(patient_count*snp_ptm_id_count)) {
  pep_w_snp_long <- c(pep_w_snp_long, rep(1, pep_w_snp_count[i]), rep(0, pep_count[i] - pep_w_snp_count[i]))
}

pep_w_ptm_long <- numeric(0)
for (i in 1:(patient_count * snp_ptm_id_count)) {
  pep_w_ptm_long <- c(pep_w_ptm_long, rep(1, pep_w_ptm_snp[i]), rep(0, pep_w_snp_count[i] - pep_w_ptm_snp[i]), rep(1, pep_w_ptm_nosnp[i]), rep(0, pep_count[i] - (pep_w_snp_count[i] + pep_w_ptm_nosnp[i])))
}

```


```{r dat}

# Convert the data to matrix form, this is the original form
dat = data.frame(snp_ptm_id = rep(1:snp_ptm_id_count, patient_count),
                 patient = rep(1:patient_count, each = snp_ptm_id_count), peptide = pep_count,
                 snp = pep_w_snp_count, non_snp = pep_count - pep_w_snp_count, snp_ptm = pep_w_ptm_snp, non_snp_ptm = pep_w_ptm_nosnp)
dat <- dat %>% mutate(effect_size = effect_size[snp_ptm_id])
dat = as_tibble(dat)
dat

#original form expanded out by number of peptides
dat_long <- data.frame(snp_ptm_id = rep(rep(1:snp_ptm_id_count, patient_count), pep_count), 
                     patient = rep(rep(1:patient_count, each = snp_ptm_id_count), pep_count),
                     snp = pep_w_snp_long, ptm = pep_w_ptm_long)
dat_long <- dat_long %>% mutate(effect_size = effect_size[snp_ptm_id])
dat_long <- as_tibble(dat_long)
dat_long

# Convert to a coarser form
dat_coarse = dat
dat_coarse$snp_type = cut(dat_coarse$snp/dat_coarse$peptide, breaks = c(-Inf, 0.33, 0.66, Inf), labels = c(0, 0.5, 1), include.lowest = TRUE)
dat_coarse$snp_type <- (as.numeric(dat_coarse$snp_type) - 1) / 2
dat_coarse$effect_size = dat_coarse$effect_size
dat_coarse$snp_ptm <- (dat_coarse$snp_ptm + dat_coarse$non_snp_ptm) / dat_coarse$peptide
dat_coarse = dat_coarse %>% select(snp_ptm_id, patient, peptide, snp_type, snp_ptm, effect_size)
dat_coarse

```

```{r lin_reg}

#coarse data linear regression model
coarse_lm_b <- numeric(snp_ptm_id_count)
coarse_lm_pval <- numeric(snp_ptm_id_count)

for (idc in 1:snp_ptm_id_count) {
  subset_data <- subset(dat_coarse, snp_ptm_id == idc)
  if(all(subset_data$snp_ptm == 0) | all(subset_data$snp_type == 0)) {
    coarse_lm_b[idc] <- NA
    coarse_lm_pval[idc] <- NA
  } else {
    coarse_lm <- lm(snp_ptm ~ snp_type, data = subset_data)
    coarse_lm_pval[idc] <- summary(coarse_lm)$coefficients[2,4]
    coarse_lm_b[idc] <- coef(coarse_lm)[2]
  }
}

#coarse data snp-ptm ID vs p-value plot
sig_col <- ifelse(coarse_lm_pval < 0.05, "red", "black")
plot(seq_len(snp_ptm_id_count), coarse_lm_pval, main = "Significance of snp-ptm correlation (coarse)",
     xlab = "snp-ptm id", ylab = "p-value", pch = 20, col = sig_col)
abline(h = 0.05, col = "red4")

```

```{r oldlinreg}

#old data linear regression model
old_lm_b <- numeric(snp_ptm_id_count)
old_lm_pval <- numeric(snp_ptm_id_count)

for (idc in 1:snp_ptm_id_count) {
  subset_data <- subset(dat_long, snp_ptm_id == idc)
  if(all(subset_data$snp == 0) | all(subset_data$ptm == 0)) {
    old_lm_b[idc] <- NA
    old_lm_pval[idc] <- NA
  } else {
    old_lm <- lm(ptm ~ snp, data = subset_data)
    old_lm_pval[idc] <- summary(old_lm)$coefficients[2,4]
    old_lm_b[idc] <- coef(old_lm)[2]
  }
}

#old data snp-ptm ID vs p-value plot
sig_col_2 <- ifelse(old_lm_pval < 0.05, "blue", "black")
plot(seq_len(snp_ptm_id_count), old_lm_pval, main = "Significance of snp-ptm correlation (old)",
     xlab = "snp-ptm id", ylab = "p-value", pch = 20, col = sig_col_2)
abline(h = 0.05, col = "blue4")

```

```{r p_vals}
#table of significant p-values
old_sig_pvals <- which(old_lm_pval <= 0.05)
coarse_sig_pvals <- which(coarse_lm_pval <= 0.05)
all_sig_pvals <- union(old_sig_pvals, coarse_sig_pvals)
df_sig_pvals <- data.frame("sig_pval_id" = all_sig_pvals,
      "coarse" = all_sig_pvals %in% coarse_sig_pvals,
      "old" = all_sig_pvals %in% old_sig_pvals,
      "effect_size" = effect_size[all_sig_pvals])

df_sig_pvals

#table of differences
diff_ind <- (seq_len(snp_ptm_id_count))[!((coarse_lm_pval > 0.05) == (old_lm_pval > 0.05))]
diff_ind <- diff_ind[!is.na(diff_ind)]
pval_diff <- data.frame("snp_ptm_id" = diff_ind,
      "effect_size" = effect_size[diff_ind],
      "coarse" = coarse_lm_pval[diff_ind],
      "old" = old_lm_pval[diff_ind])
pval_diff$"sig_group" <- ifelse(pval_diff$old <= 0.05, "old", "coarse")
pval_diff <- pval_diff %>% relocate(sig_group, .after = snp_ptm_id)

pval_diff

#count summary table
sig_old <- sum(pval_diff$old <= 0.05)
sig_coarse <- sum(pval_diff$coarse <= 0.05)
pval_diff_summary <- data.frame("sig_val_count" = c(length(old_sig_pvals), length(coarse_sig_pvals), length(all_sig_pvals)),
      "diff_sig_vals" = c(sig_old, sig_coarse, sig_old + sig_coarse),
      "diff_sig_val_ratio" = c(sig_old/length(diff_ind),
            sig_coarse/length(diff_ind),
            sig_old/length(diff_ind) + sig_coarse/length(diff_ind)),
      row.names = c("old_diff", "coarse_diff", "total"))

pval_diff_summary

#effect size summary
minus_effect <- sum(effect_size[all_sig_pvals] == -0.2)
zero_effect <- sum(effect_size[all_sig_pvals] == 0)
plus_effect <- sum(effect_size[all_sig_pvals] == 0.2)
effect_data <- data.frame("negative_effect" = c(minus_effect, minus_effect / length(effect_size[all_sig_pvals])),
      "no_effect" = c(zero_effect, zero_effect / length(effect_size[all_sig_pvals])),
      "positive_effect" = c(plus_effect, plus_effect / length(effect_size[all_sig_pvals])),
      row.names = c("count", "proportion"))

effect_data


```

for each dataset, get significant p-values, compare intersection between sets
how many significant snp-ptm id have positive effect size (get effect size for all sig p val)
compare B and eff size with correlation
visualize nicely (think of how to present multiple effect sizes)

```{r b_eff_cor}

old_b_eff_lm <- lm(old_lm_b ~ effect_size)
coarse_b_eff_lm <- lm(coarse_lm_b ~ effect_size)

plot(effect_size, old_lm_b, ylab = "b_value",
     main = "lm b-val vs effect size (old)", cex = 0.9, col = "blue")
abline(old_b_eff_lm)
text(x=-0.1, y=0.2, labels = paste("adj r2 = ", round(summary(old_b_eff_lm)$adj.r.squared, 4)))

plot(effect_size, coarse_lm_b, ylab = "b_value",
     main = "lm b-val vs effect size (coarse)", cex = 0.9, col = "red")
abline(coarse_b_eff_lm)
text(x=-0.1, y=0.2, labels = paste("adj r2 = ", round(summary(coarse_b_eff_lm)$adj.r.squared, 4)))


```

```{r vary_eff_size}

eff_sizes <- seq(0.05, 0.3, by = 0.05)
eff_prob2 <- matrix(nrow = 6, ncol = 3)
for (i in seq_len(nrow(eff_prob2))) {
  eff_prob2[i, ] <- c(0, 1, 0) + i*c(0.05, -0.1, 0.05)
}
effect_size2 <- matrix(nrow = length(eff_sizes), ncol = snp_ptm_id_count)
j <- 1
for (i in eff_sizes) {
  effect_size2[j, ] <- sample(c(-1*i, 0, i),
      size = snp_ptm_id_count, replace = TRUE, prob = c(0.15, 0.7, 0.15))
  j <- j + 1
}

effect_size2

```